name: Tests

on: [push, fork]

jobs:

  MakeTest:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Deploying miniconda'
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: 'latest'
      - name: 'Tests'
        run: |
          pip install pytest
          make test

  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          FILTER_REGEX_EXCLUDE: "./lib/.*"
          VALIDATE_CLANG_FORMAT: false
          VALIDATE_CPP: false
          VALIDATE_YAML: false
          DEFAULT_BRANCH: ${{ github.ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
